
package bingo.card;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Chariz
 */
public class Start extends javax.swing.JPanel {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        bingoGame = new javax.swing.JLabel();
        random = new javax.swing.JButton();
        create = new javax.swing.JButton();
        quit = new javax.swing.JButton();

        jButton2.setText("Custom Made");

        welcome.setFont(new java.awt.Font("Raleway ExtraLight", 0, 30)); // NOI18N
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("Please select your choice:");

        bingoGame.setFont(new java.awt.Font("Raleway ExtraBold", 0, 75)); // NOI18N
        bingoGame.setForeground(new java.awt.Color(255, 102, 51));
        bingoGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bingoGame.setText("Bingo Game");

        random.setBackground(new java.awt.Color(255, 255, 255));
        random.setFont(new java.awt.Font("Raleway Medium", 0, 18)); // NOI18N
        random.setText("Generate Random Card");
        random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomActionPerformed(evt);
            }
        });

        create.setBackground(new java.awt.Color(255, 255, 255));
        create.setFont(new java.awt.Font("Raleway Medium", 0, 18)); // NOI18N
        create.setText("Create Own Card");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        quit.setBackground(new java.awt.Color(255, 255, 255));
        quit.setFont(new java.awt.Font("Raleway Medium", 0, 18)); // NOI18N
        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(welcome)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(random)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(create)
                        .addGap(159, 159, 159))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bingoGame))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(quit)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(bingoGame)
                .addGap(18, 18, 18)
                .addComponent(welcome)
                .addGap(29, 29, 29)
                .addComponent(random)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(create)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(quit)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomActionPerformed
        randomCard randomCardPanel = new randomCard();
        JFrame frame = new JFrame("Random Card");
        frame.getContentPane().add(randomCardPanel);
        frame.pack();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        JFrame topLevelFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topLevelFrame.dispose();
    }//GEN-LAST:event_randomActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        customCard customCardPanel = new customCard();
        JFrame frame = new JFrame("Custom Card");
        frame.getContentPane().add(customCardPanel);
        frame.pack();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        JFrame topLevelFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        topLevelFrame.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_createActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bingoGame;
    private javax.swing.JButton create;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton quit;
    private javax.swing.JButton random;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
